README.md

Cleanup of readme content

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/ContractRestController.java

Add explicit encoding information when consuming and producing

---

src/main/java/ch/baloise/corellia/api/ContractApplication.java
src/main/java/ch/baloise/corellia/api/ContractRestController.java
src/main/java/ch/baloise/corellia/api/constraints/SizeConstraint.java
src/main/java/ch/baloise/corellia/api/entities/Address.java
src/main/java/ch/baloise/corellia/api/entities/Agent.java
src/main/java/ch/baloise/corellia/api/entities/Company.java
src/main/java/ch/baloise/corellia/api/entities/Contract.java
src/main/java/ch/baloise/corellia/api/entities/ContractReference.java
src/main/java/ch/baloise/corellia/api/entities/Coverable.java
src/main/java/ch/baloise/corellia/api/entities/Coverage.java
src/main/java/ch/baloise/corellia/api/entities/Document.java
src/main/java/ch/baloise/corellia/api/entities/ErrorResponse.java
src/main/java/ch/baloise/corellia/api/entities/FileHandle.java
src/main/java/ch/baloise/corellia/api/entities/MonetaryAmount.java
src/main/java/ch/baloise/corellia/api/entities/Payment.java
src/main/java/ch/baloise/corellia/api/entities/Person.java
src/main/java/ch/baloise/corellia/api/entities/PhoneNumber.java
src/main/java/ch/baloise/corellia/api/entities/Product.java
src/main/java/ch/baloise/corellia/api/entities/Role.java
src/main/java/ch/baloise/corellia/api/entities/ValidationError.java
src/main/java/ch/baloise/corellia/api/entities/Version.java
src/main/resources/openapi.yaml

Add license header to src files

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Person.java

Make language a mandatory field

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/ContractRestController.java

Revert "Add explicit encoding information when consuming and producing"

---

docs/CODEOWNERS

Add @matthewwardle as default PR reviewer for API spec changes.

Change default reviewers for API spec

---

src/main/java/ch/baloise/corellia/api/entities/Document.java

Added additional support for additional media types such as PNG and GIF.
- Simply added additional media types in the media types enum.
- Enforced naming convention for enums (i.e. ALL_CAPS) during this process.

JAVAMIG-4366 Support for additional media types

---

src/main/java/ch/baloise/corellia/api/entities/ErrorResponse.java

fix for #53 - create ErrorResponse fails

---

src/main/java/ch/baloise/corellia/api/constraints/SizeConstraint.java
src/main/java/ch/baloise/corellia/api/entities/Company.java

Fixes #57 
- Add CrediReform as legal-form field to company interface

- Add LegalForm field

---

docs/openapi.json
docs/swagger.json

Fixes baloise/corellia#57 - legalForm fix - regenerate json files

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/constraints/SizeConstraint.java
src/main/java/ch/baloise/corellia/api/entities/Contract.java
src/main/java/ch/baloise/corellia/api/entities/ContractReference.java
src/main/java/ch/baloise/corellia/api/entities/ErrorResponse.java
src/main/java/ch/baloise/corellia/api/entities/Product.java

- Sync API constrains with backend constrains

Sync constrains with actual system implementation

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Agent.java

Fixes #64 
- field is now optional

Make "agent.email" field optional

---

pom.xml

Unify groupdId and artifactId to package structure

---

Jenkinsfile

Fixes wrong artifact id for software composition analysis tooling.

Fix artifactId

---

docs/PULL_REQUEST_TEMPLATE.md

Reduced DoD requirements - the rest is internal

---

pom.xml

manually released to version 1.0.1

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Company.java
src/main/java/ch/baloise/corellia/api/entities/Person.java
src/main/java/ch/baloise/corellia/api/entities/Role.java

https://github.com/baloise/corellia/issues/88
Refactor partner handling.

Refactor API to include partnerNr in company and person

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Identifier.java

Fixes #
Useage of enum instead of string.

Change identifier type from string to enum

---

src/main/java/ch/baloise/corellia/api/entities/Document.java

Fixes #93
- Rename documenttype from INTERNE_KORRESPONDENZ to COVER_LETTER

#93 rename interne korrespondenz to cover letter

---

README.md

Fixes #
- documented the release process

documented release process

---

pom.xml

Fixes #
- changed distribution url

changed distribution url

---

docs/openapi.json
src/main/java/ch/baloise/corellia/api/entities/ErrorResponse.java

Fixes #
- added a default constructor

added a default constructor to ErrorResponse

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Contract.java

- Remove conditionMonthYear on V2 as it's replaced by terms of services

Remove conditionMonthYear from V2 contact

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Document.java

Fixes #
Add better description for already existing constraint.

Add constraint description for document data contracts

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/constraints/SizeConstraint.java
src/main/java/ch/baloise/corellia/api/entities/Contract.java

Needed for migration contracts which will not send a new document to the customer
Fixes #
Now an empty file handle list is allowed
-
-

CHIST-1996: it's allowed to send 0 documents for a contract.

---

docs/openapi.json
docs/swagger.json
src/main/java/ch/baloise/corellia/api/entities/Coverage.java

Add measurandType, measurandValue, discountType, discountValue, extraChargeType, extraChargeValue to Coverage
[Link to requirement](https://confluence.baloisenet.com/atlassian/display/CHIST/Additional+fields+for+agriculture+liability)

[BABEL-1675] - Add measurandType, measurandValue,

---

docs/openapi.json
src/main/java/ch/baloise/corellia/api/entities/Coverage.java

change type to accept Integer instead of int in order to accept null value
Fixes #
-
-

[BABEL-1675] - change type to accept Integer instead of int in order to accept null value
